# Dependencies
markdown:         kramdown
highlighter:      rouge

kramdown:
  auto_ids: true

# Permalinks
permalink:        pretty

gems:
  - jekyll-redirect-from
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock

baseurl: ""
url: ""

# Info
title: Microshare
description: Store, Protect & Share the data you want, the way you want.
email: docs@microshare.io
twitter: microshare_io
github: microshare
social_logo_path: /assets/brand/default-icon.png
social_image_path: /assets/brand/default-icon.png

# Custom vars
current_version:  2
docs_version:     2
repo:             https://github.com/microshare/microshare.github.io
blog:             https://microshare.io/blog

###

#url: "https://microshare.io" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: microshare_io
#github_username:  microshare
#github_url: "https://github.com/microshare"

# _redirects file for Netlify should be included
#include: ["_redirects"]

# Build settings
#plugins:
#  - jekyll-feed

#sass:
#  style: compressed

# Pages permalink
#defaults:
#  -
#    scope:
#      type: "posts"
#    values:
#      permalink: /blog/:year/:month/:day/:title/
